/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as verifierSol from "./Verifier.sol";
export type { verifierSol };
export type { MicroGig } from "./MicroGig";
export * as factories from "./factories";
export { MicroGig__factory } from "./factories/MicroGig__factory";
export type { Groth16Verifier } from "./Verifier.sol/Groth16Verifier";
export { Groth16Verifier__factory } from "./factories/Verifier.sol/Groth16Verifier__factory";
