/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "./common";

export interface MicroGigInterface extends utils.Interface {
  functions: {
    "assignFreelancer(uint256,address)": FunctionFragment;
    "completeJob(uint256,uint256[2],uint256[2][2],uint256[2],uint256[3])": FunctionFragment;
    "createJob(uint256,uint256)": FunctionFragment;
    "depositPayment(uint256)": FunctionFragment;
    "jobCount()": FunctionFragment;
    "jobs(uint256)": FunctionFragment;
    "releasePayment(uint256)": FunctionFragment;
    "verifier()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "assignFreelancer"
      | "completeJob"
      | "createJob"
      | "depositPayment"
      | "jobCount"
      | "jobs"
      | "releasePayment"
      | "verifier"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "assignFreelancer",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "completeJob",
    values: [
      PromiseOrValue<BigNumberish>,
      [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      [
        [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
        [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
      ],
      [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      [
        PromiseOrValue<BigNumberish>,
        PromiseOrValue<BigNumberish>,
        PromiseOrValue<BigNumberish>
      ]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "createJob",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "depositPayment",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(functionFragment: "jobCount", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "jobs",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "releasePayment",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(functionFragment: "verifier", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "assignFreelancer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "completeJob",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "createJob", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "depositPayment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "jobCount", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "jobs", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "releasePayment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "verifier", data: BytesLike): Result;

  events: {
    "FreelancerAssigned(uint256,address)": EventFragment;
    "JobCompleted(uint256)": EventFragment;
    "JobCreated(uint256)": EventFragment;
    "PaymentDeposited(uint256)": EventFragment;
    "PaymentReleased(uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "FreelancerAssigned"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "JobCompleted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "JobCreated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "PaymentDeposited"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "PaymentReleased"): EventFragment;
}

export interface FreelancerAssignedEventObject {
  jobId: BigNumber;
  freelancer: string;
}
export type FreelancerAssignedEvent = TypedEvent<
  [BigNumber, string],
  FreelancerAssignedEventObject
>;

export type FreelancerAssignedEventFilter =
  TypedEventFilter<FreelancerAssignedEvent>;

export interface JobCompletedEventObject {
  jobId: BigNumber;
}
export type JobCompletedEvent = TypedEvent<
  [BigNumber],
  JobCompletedEventObject
>;

export type JobCompletedEventFilter = TypedEventFilter<JobCompletedEvent>;

export interface JobCreatedEventObject {
  jobId: BigNumber;
}
export type JobCreatedEvent = TypedEvent<[BigNumber], JobCreatedEventObject>;

export type JobCreatedEventFilter = TypedEventFilter<JobCreatedEvent>;

export interface PaymentDepositedEventObject {
  jobId: BigNumber;
}
export type PaymentDepositedEvent = TypedEvent<
  [BigNumber],
  PaymentDepositedEventObject
>;

export type PaymentDepositedEventFilter =
  TypedEventFilter<PaymentDepositedEvent>;

export interface PaymentReleasedEventObject {
  jobId: BigNumber;
}
export type PaymentReleasedEvent = TypedEvent<
  [BigNumber],
  PaymentReleasedEventObject
>;

export type PaymentReleasedEventFilter = TypedEventFilter<PaymentReleasedEvent>;

export interface MicroGig extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: MicroGigInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    assignFreelancer(
      _jobId: PromiseOrValue<BigNumberish>,
      _freelancer: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    completeJob(
      _jobId: PromiseOrValue<BigNumberish>,
      _pA: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      _pB: [
        [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
        [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
      ],
      _pC: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      _pubSignals: [
        PromiseOrValue<BigNumberish>,
        PromiseOrValue<BigNumberish>,
        PromiseOrValue<BigNumberish>
      ],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    createJob(
      _reward: PromiseOrValue<BigNumberish>,
      _requiredSkill: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    depositPayment(
      _jobId: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    jobCount(overrides?: CallOverrides): Promise<[BigNumber]>;

    jobs(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, string, string, BigNumber, BigNumber, number] & {
        id: BigNumber;
        employer: string;
        freelancer: string;
        reward: BigNumber;
        requiredSkill: BigNumber;
        status: number;
      }
    >;

    releasePayment(
      _jobId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    verifier(overrides?: CallOverrides): Promise<[string]>;
  };

  assignFreelancer(
    _jobId: PromiseOrValue<BigNumberish>,
    _freelancer: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  completeJob(
    _jobId: PromiseOrValue<BigNumberish>,
    _pA: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
    _pB: [
      [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
    ],
    _pC: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
    _pubSignals: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  createJob(
    _reward: PromiseOrValue<BigNumberish>,
    _requiredSkill: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  depositPayment(
    _jobId: PromiseOrValue<BigNumberish>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  jobCount(overrides?: CallOverrides): Promise<BigNumber>;

  jobs(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, string, string, BigNumber, BigNumber, number] & {
      id: BigNumber;
      employer: string;
      freelancer: string;
      reward: BigNumber;
      requiredSkill: BigNumber;
      status: number;
    }
  >;

  releasePayment(
    _jobId: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  verifier(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    assignFreelancer(
      _jobId: PromiseOrValue<BigNumberish>,
      _freelancer: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    completeJob(
      _jobId: PromiseOrValue<BigNumberish>,
      _pA: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      _pB: [
        [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
        [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
      ],
      _pC: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      _pubSignals: [
        PromiseOrValue<BigNumberish>,
        PromiseOrValue<BigNumberish>,
        PromiseOrValue<BigNumberish>
      ],
      overrides?: CallOverrides
    ): Promise<void>;

    createJob(
      _reward: PromiseOrValue<BigNumberish>,
      _requiredSkill: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    depositPayment(
      _jobId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    jobCount(overrides?: CallOverrides): Promise<BigNumber>;

    jobs(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, string, string, BigNumber, BigNumber, number] & {
        id: BigNumber;
        employer: string;
        freelancer: string;
        reward: BigNumber;
        requiredSkill: BigNumber;
        status: number;
      }
    >;

    releasePayment(
      _jobId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    verifier(overrides?: CallOverrides): Promise<string>;
  };

  filters: {
    "FreelancerAssigned(uint256,address)"(
      jobId?: null,
      freelancer?: null
    ): FreelancerAssignedEventFilter;
    FreelancerAssigned(
      jobId?: null,
      freelancer?: null
    ): FreelancerAssignedEventFilter;

    "JobCompleted(uint256)"(jobId?: null): JobCompletedEventFilter;
    JobCompleted(jobId?: null): JobCompletedEventFilter;

    "JobCreated(uint256)"(jobId?: null): JobCreatedEventFilter;
    JobCreated(jobId?: null): JobCreatedEventFilter;

    "PaymentDeposited(uint256)"(jobId?: null): PaymentDepositedEventFilter;
    PaymentDeposited(jobId?: null): PaymentDepositedEventFilter;

    "PaymentReleased(uint256)"(jobId?: null): PaymentReleasedEventFilter;
    PaymentReleased(jobId?: null): PaymentReleasedEventFilter;
  };

  estimateGas: {
    assignFreelancer(
      _jobId: PromiseOrValue<BigNumberish>,
      _freelancer: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    completeJob(
      _jobId: PromiseOrValue<BigNumberish>,
      _pA: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      _pB: [
        [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
        [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
      ],
      _pC: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      _pubSignals: [
        PromiseOrValue<BigNumberish>,
        PromiseOrValue<BigNumberish>,
        PromiseOrValue<BigNumberish>
      ],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    createJob(
      _reward: PromiseOrValue<BigNumberish>,
      _requiredSkill: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    depositPayment(
      _jobId: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    jobCount(overrides?: CallOverrides): Promise<BigNumber>;

    jobs(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    releasePayment(
      _jobId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    verifier(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    assignFreelancer(
      _jobId: PromiseOrValue<BigNumberish>,
      _freelancer: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    completeJob(
      _jobId: PromiseOrValue<BigNumberish>,
      _pA: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      _pB: [
        [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
        [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
      ],
      _pC: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      _pubSignals: [
        PromiseOrValue<BigNumberish>,
        PromiseOrValue<BigNumberish>,
        PromiseOrValue<BigNumberish>
      ],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    createJob(
      _reward: PromiseOrValue<BigNumberish>,
      _requiredSkill: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    depositPayment(
      _jobId: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    jobCount(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    jobs(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    releasePayment(
      _jobId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    verifier(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
